from typing import Protocol
from api.contracts import EvidenceCreateInput, EvidenceOutput, ExecutionContext, OperationResult


class EvidenceServiceInterface(Protocol):
    def get_by_id(self, context: ExecutionContext, evidence_id: int) -> OperationResult[EvidenceOutput]: ...
    def list_by_ticket(self, context: ExecutionContext, ticket_id: int) -> OperationResult[list[EvidenceOutput]]: ...
    def list_by_ticket_and_uploader(self, context: ExecutionContext, ticket_id: int, uploaded_by: int) -> OperationResult[list[EvidenceOutput]]: ...
    def create_metadata(self, context: ExecutionContext, data: EvidenceCreateInput) -> OperationResult[EvidenceOutput]: ...
