from typing import Protocol
from api.contracts import ExecutionContext, HistoryEventCreateInput, HistoryEventOutput, OperationResult


class HistoryServiceInterface(Protocol):
    def get_event(self, context: ExecutionContext, event_id: int) -> OperationResult[HistoryEventOutput]: ...
    def list_by_ticket(self, context: ExecutionContext, ticket_id: int) -> OperationResult[list[HistoryEventOutput]]: ...
    def create_event(self, context: ExecutionContext, data: HistoryEventCreateInput) -> OperationResult[HistoryEventOutput]: ...
