from typing import Protocol
from api.models import Commune

class CommuneRepositoryInterface(Protocol):
    def get_by_id(self, commune_id: int) -> Commune | None: ...
    def get_by_municipality_and_number(self, municipality_id: int, number: int) -> Commune | None: ...
    def list_by_municipality(self, municipality_id: int) -> list[Commune]: ...
