from typing import Protocol
from api.models import Municipality

class MunicipalityRepositoryInterface(Protocol):
    def get_by_id(self, municipality_id: int) -> Municipality | None: ...
    def get_by_name(self, name: str) -> Municipality | None: ...
    def list_all(self) -> list[Municipality]: ...
