from typing import Protocol
from api.models import Neighborhood

class NeighborhoodRepositoryInterface(Protocol):
    def get_by_id(self, neighborhood_id: int) -> Neighborhood | None: ...
    def list_by_municipality(self, municipality_id: int) -> list[Neighborhood]: ...
    def list_by_commune(self, commune_id: int) -> list[Neighborhood]: ...
    def list_without_commune(self, municipality_id: int) -> list[Neighborhood]: ...
