"""Model for municipalities."""

from dataclasses import dataclass


@dataclass(frozen=True)
class Municipality:
    """Row from municipalities; id is generated by SERIAL."""

    id: int
    name: str
