from typing import Protocol
from api.contracts import (
    ActionOutput, CommuneOutput, CrossBisCodeOutput, CrossQuadrantOutput,
    CrossSuffixLetterOutput, ExecutionContext, FailureTypeOutput,
    MunicipalityOutput, NeighborhoodOutput, OperationResult, PriorityOutput,
    RoadBisCodeOutput, RoadQuadrantOutput, RoadSuffixLetterOutput,
    RoadTypeOutput, RoleOutput, StatusOutput,
)


class CatalogServiceInterface(Protocol):
    def list_municipalities(self, context: ExecutionContext) -> OperationResult[list[MunicipalityOutput]]: ...
    def list_communes(self, context: ExecutionContext, municipality_id: int) -> OperationResult[list[CommuneOutput]]: ...
    def list_neighborhoods_by_municipality(self, context: ExecutionContext, municipality_id: int) -> OperationResult[list[NeighborhoodOutput]]: ...
    def list_neighborhoods_by_commune(self, context: ExecutionContext, commune_id: int) -> OperationResult[list[NeighborhoodOutput]]: ...
    def list_neighborhoods_without_commune(self, context: ExecutionContext, municipality_id: int) -> OperationResult[list[NeighborhoodOutput]]: ...
    def list_road_types(self, context: ExecutionContext) -> OperationResult[list[RoadTypeOutput]]: ...
    def list_road_suffix_letters(self, context: ExecutionContext) -> OperationResult[list[RoadSuffixLetterOutput]]: ...
    def list_road_bis_codes(self, context: ExecutionContext) -> OperationResult[list[RoadBisCodeOutput]]: ...
    def list_road_quadrants(self, context: ExecutionContext) -> OperationResult[list[RoadQuadrantOutput]]: ...
    def list_cross_suffix_letters(self, context: ExecutionContext) -> OperationResult[list[CrossSuffixLetterOutput]]: ...
    def list_cross_bis_codes(self, context: ExecutionContext) -> OperationResult[list[CrossBisCodeOutput]]: ...
    def list_cross_quadrants(self, context: ExecutionContext) -> OperationResult[list[CrossQuadrantOutput]]: ...
    def list_roles(self, context: ExecutionContext) -> OperationResult[list[RoleOutput]]: ...
    def list_priorities(self, context: ExecutionContext) -> OperationResult[list[PriorityOutput]]: ...
    def list_failure_types(self, context: ExecutionContext) -> OperationResult[list[FailureTypeOutput]]: ...
    def list_failure_types_by_priority(self, context: ExecutionContext, priority_id: int) -> OperationResult[list[FailureTypeOutput]]: ...
    def list_statuses(self, context: ExecutionContext) -> OperationResult[list[StatusOutput]]: ...
    def list_actions(self, context: ExecutionContext) -> OperationResult[list[ActionOutput]]: ...
