from typing import Protocol
from api.models import Action

class ActionRepositoryInterface(Protocol):
    def get_by_id(self, record_id: int) -> Action | None: ...
    def get_by_name(self, name: str) -> Action | None: ...
    def list_all(self) -> list[Action]: ...
