from typing import Protocol
from api.contracts import EvidenceCreateInput
from api.models import Evidence

class EvidenceRepositoryInterface(Protocol):
    def get_by_id(self, evidence_id: int) -> Evidence | None: ...
    def list_by_ticket(self, ticket_id: int) -> list[Evidence]: ...
    def list_by_ticket_and_uploader(self, ticket_id: int, uploaded_by: int) -> list[Evidence]: ...
    def create(self, data: EvidenceCreateInput) -> Evidence: ...
