from typing import Protocol
from api.models import FailureType

class FailureTypeRepositoryInterface(Protocol):
    def get_by_id(self, failure_type_id: int) -> FailureType | None: ...
    def list_all(self) -> list[FailureType]: ...
    def list_by_priority(self, priority_id: int) -> list[FailureType]: ...
