from typing import Protocol
from api.contracts import HistoryEventCreateInput
from api.models import HistoryEvent

class HistoryEventRepositoryInterface(Protocol):
    def get_by_id(self, event_id: int) -> HistoryEvent | None: ...
    def list_by_ticket(self, ticket_id: int) -> list[HistoryEvent]: ...
    def create(self, data: HistoryEventCreateInput) -> HistoryEvent: ...
