from typing import Protocol
from api.models import Priority

class PriorityRepositoryInterface(Protocol):
    def get_by_id(self, record_id: int) -> Priority | None: ...
    def get_by_name(self, name: str) -> Priority | None: ...
    def list_all(self) -> list[Priority]: ...
