from typing import Protocol
from api.models import Status

class StatusRepositoryInterface(Protocol):
    def get_by_id(self, record_id: int) -> Status | None: ...
    def get_by_name(self, name: str) -> Status | None: ...
    def list_all(self) -> list[Status]: ...
