from typing import Protocol
from api.contracts import TicketCreateInput, TicketFilters, TicketUpdateInput
from api.models import Ticket

class TicketRepositoryInterface(Protocol):
    def get_by_id(self, ticket_id: int) -> Ticket | None: ...
    def get_by_code(self, code: str) -> Ticket | None: ...
    def list_by_filters(self, filters: TicketFilters | None = None) -> list[Ticket]: ...
    def create(self, data: TicketCreateInput) -> Ticket: ...
    def update(self, data: TicketUpdateInput) -> Ticket | None: ...
