from typing import Protocol
from api.contracts import AddressComponentsInput, AddressCreateInput, AddressOutput, ExecutionContext, OperationResult


class AddressServiceInterface(Protocol):
    def get_by_id(self, context: ExecutionContext, address_id: int) -> OperationResult[AddressOutput]: ...
    def find_by_components(self, context: ExecutionContext, components: AddressComponentsInput) -> OperationResult[AddressOutput | None]: ...
    def create_or_reuse(self, context: ExecutionContext, data: AddressCreateInput) -> OperationResult[AddressOutput]: ...
    def format_address(self, context: ExecutionContext, address_id: int) -> OperationResult[str]: ...
