"""Typed data contracts shared by SGF-AP API layers."""

from .address.address_types import AddressComponentsInput, AddressCreateInput, AddressOutput
from .catalog_types import (
    ActionOutput,
    ActionLookupInput,
    CrossBisCodeOutput,
    CrossQuadrantOutput,
    CrossSuffixLetterOutput,
    FailureTypeOutput,
    FailureTypeLookupInput,
    PriorityLookupInput,
    PriorityOutput,
    RoadBisCodeOutput,
    RoadQuadrantOutput,
    RoadSuffixLetterOutput,
    RoadTypeOutput,
    RoleOutput,
    RoleLookupInput,
    StatusOutput,
    StatusLookupInput,
    TextCodeLookupInput,
)
from .actor_context import ActorContext
from .common_types import UNSET, Unset, ensure_aware
from .users.crew_member_types import CrewMemberInput, CrewMemberOutput, CrewMembershipResult
from .users.crew_types import CrewCreateInput, CrewOutput, CrewUpdateInput
from .error_types import ErrorDetail, ErrorOutput
from .execution_context import ACTOR_REQUIRED_OPERATIONS, ExecutionContext, requires_actor, validate_actor_context
from .geolocation.geolocation_types import (
    CommuneByIdInput,
    CommuneLookupInput,
    CommuneOutput,
    MunicipalityLookupInput,
    MunicipalityOutput,
    NeighborhoodByIdInput,
    NeighborhoodLookupInput,
    NeighborhoodOutput,
)
from .tickets.evidence_types import EvidenceCreateInput, EvidenceOutput, EvidenceLookupInput
from .tickets.history_event_types import HistoryEventCreateInput, HistoryEventLookupInput, HistoryEventOutput
from .operation_result import OperationResult
from .tickets.ticket_types import (
    TicketAssignmentInput,
    TicketAttentionInput,
    TicketClosureReviewInput,
    TicketCodeLookupInput,
    TicketCreateInput,
    TicketUpdateInput,
    TicketLookupInput,
    TicketOperationInput,
    TicketOutput,
)
from .users.user_types import UserActivationInput, UserCreateInput, UserOutput, UserUpdateInput

__all__ = [
    "UNSET",
    "Unset",
    "ensure_aware",
    "ActorContext",
    "AddressComponentsInput",
    "AddressCreateInput",
    "AddressOutput",
    "ActionOutput",
    "ActionLookupInput",
    "CrossBisCodeOutput",
    "CrossQuadrantOutput",
    "CrossSuffixLetterOutput",
    "FailureTypeOutput",
    "FailureTypeLookupInput",
    "PriorityLookupInput",
    "PriorityOutput",
    "RoadBisCodeOutput",
    "RoadQuadrantOutput",
    "RoadSuffixLetterOutput",
    "RoadTypeOutput",
    "RoleOutput",
    "RoleLookupInput",
    "StatusOutput",
    "StatusLookupInput",
    "TextCodeLookupInput",
    "CrewMemberInput",
    "CrewMemberOutput",
    "CrewMembershipResult",
    "CrewCreateInput",
    "CrewOutput",
    "CrewUpdateInput",
    "ErrorDetail",
    "ErrorOutput",
    "ExecutionContext",
    "ACTOR_REQUIRED_OPERATIONS",
    "requires_actor",
    "validate_actor_context",
    "CommuneByIdInput",
    "CommuneLookupInput",
    "CommuneOutput",
    "MunicipalityLookupInput",
    "MunicipalityOutput",
    "NeighborhoodByIdInput",
    "NeighborhoodLookupInput",
    "NeighborhoodOutput",
    "EvidenceCreateInput",
    "EvidenceLookupInput",
    "EvidenceOutput",
    "HistoryEventCreateInput",
    "HistoryEventLookupInput",
    "HistoryEventOutput",
    "OperationResult",
    "TicketAssignmentInput",
    "TicketAttentionInput",
    "TicketClosureReviewInput",
    "TicketCodeLookupInput",
    "TicketCreateInput",
    "TicketUpdateInput",
    "TicketLookupInput",
    "TicketOperationInput",
    "TicketOutput",
    "UserActivationInput",
    "UserCreateInput",
    "UserOutput",
    "UserUpdateInput",
]
