from typing import Protocol
from api.contracts import CrewMemberInput
from api.models import CrewMember

class CrewMemberRepositoryInterface(Protocol):
    def get_by_user_id(self, user_id: int) -> CrewMember | None: ...
    def list_by_crew(self, crew_id: int) -> list[CrewMember]: ...
    def create(self, data: CrewMemberInput) -> CrewMember: ...
    def update_crew(self, user_id: int, crew_id: int) -> CrewMember | None: ...
    def remove(self, user_id: int) -> bool: ...
