from typing import Protocol
from api.contracts import CrewCreateInput, CrewUpdateInput
from api.models import Crew

class CrewRepositoryInterface(Protocol):
    def get_by_id(self, crew_id: int) -> Crew | None: ...
    def list_all(self) -> list[Crew]: ...
    def create(self, data: CrewCreateInput) -> Crew: ...
    def update(self, data: CrewUpdateInput) -> Crew | None: ...
