from typing import Protocol
from api.models import Role

class RoleRepositoryInterface(Protocol):
    def get_by_id(self, record_id: int) -> Role | None: ...
    def get_by_name(self, name: str) -> Role | None: ...
    def list_all(self) -> list[Role]: ...
