from typing import Protocol
from api.contracts import UserActivationInput, UserCreateInput, UserFilters, UserUpdateInput
from api.models import User

class UserRepositoryInterface(Protocol):
    def get_by_id(self, user_id: int) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def list_by_filters(self, filters: UserFilters | None = None) -> list[User]: ...
    def create(self, data: UserCreateInput) -> User: ...
    def update(self, data: UserUpdateInput) -> User | None: ...
    def set_active(self, data: UserActivationInput) -> User | None: ...
