
CREATE TABLE municipalities (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);


INSERT INTO municipalities (id, name) VALUES
    (1, 'Medellín'),
    (2, 'Bello'),
    (3, 'Envigado'),
    (4, 'Itagüí'),
    (5, 'Sabaneta'),
    (6, 'La Estrella'),
    (7, 'Caldas'),
    (8, 'Copacabana'),
    (9, 'Girardota'),
    (10, 'Barbosa');





CREATE TABLE communes (
    id SERIAL PRIMARY KEY,
    number SMALLINT NOT NULL,
    name TEXT,
    municipality_id INT NOT NULL REFERENCES municipalities(id),
    UNIQUE (municipality_id, number),
    UNIQUE (municipality_id, name),
    UNIQUE (id, municipality_id)
);



INSERT INTO communes (id, number, name, municipality_id) VALUES
    (1, 1, 'Popular', 1),
    (2, 2, 'Santa Cruz', 1),
    (3, 3, 'Manrique', 1),
    (4, 4, 'Aranjuez', 1),
    (5, 5, 'Castilla', 1),
    (6, 6, 'Doce de Octubre', 1),
    (7, 7, 'Robledo', 1),
    (8, 8, 'Villa Hermosa', 1),
    (9, 9, 'Buenos Aires', 1),
    (10, 10, 'La Candelaria', 1),
    (11, 11, 'Laureles - Estadio', 1),
    (12, 12, 'La América', 1),
    (13, 13, 'San Javier', 1),
    (14, 14, 'El Poblado', 1),
    (15, 15, 'Guayabal', 1),
    (16, 16, 'Belén', 1),

    (17, 1, 'París', 2),
    (18, 2, 'Madera', 2),
    (19, 3, 'Santa Ana', 2),
    (20, 4, 'Suárez', 2),
    (21, 5, 'La Cumbre', 2),
    (22, 6, 'Bellavista', 2),
    (23, 7, 'Altos de Niquía', 2),
    (24, 8, 'Niquía', 2),
    (25, 9, 'Guasimalito', 2),
    (26, 10, 'Fontidueño', 2),
    (27, 11, 'Zamora', 2),

    (28, 1, NULL, 4),
    (29, 2, NULL, 4),
    (30, 3, NULL, 4),
    (31, 4, NULL, 4),
    (32, 5, NULL, 4),
    (33, 6, NULL, 4),
    (34, 7, NULL, 4);




CREATE TABLE neighborhoods (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    municipality_id INT NOT NULL REFERENCES municipalities(id),
    commune_id INT,
    UNIQUE (name, commune_id),
    FOREIGN KEY (commune_id, municipality_id)
        REFERENCES communes(id, municipality_id)
);



CREATE UNIQUE INDEX neighborhoods_without_commune_name_key
    ON neighborhoods (municipality_id, name)
    WHERE commune_id IS NULL;


-- MEDELLIN
INSERT INTO neighborhoods (name, municipality_id, commune_id) VALUES
    ('Aldea Pablo VI', 1, 1),
    ('Carpinelo', 1, 1),
    ('El Compromiso', 1, 1),
    ('Granizal', 1, 1),
    ('La Avanzada', 1, 1),
    ('La Esperanza No. 2', 1, 1),
    ('Moscú No. 2', 1, 1),
    ('Popular', 1, 1),
    ('San Pablo', 1, 1),
    ('Santo Domingo Savio No. 1', 1, 1),
    ('Santo Domingo Savio No. 2', 1, 1),
    ('Villa de Guadalupe', 1, 1),

    ('Andalucía', 1, 2),
    ('El Playón de los Comuneros', 1, 2),
    ('La Francia', 1, 2),
    ('La Frontera', 1, 2),
    ('La Isla', 1, 2),
    ('La Rosa', 1, 2),
    ('Moscú No. 1', 1, 2),
    ('Pablo VI', 1, 2),
    ('Santa Cruz', 1, 2),
    ('Villa Niza', 1, 2),
    ('Villa del Socorro', 1, 2),

    ('Campo Valdés No. 2', 1, 3),
    ('El Pomar', 1, 3),
    ('La Cruz', 1, 3),
    ('La Salle', 1, 3),
    ('Las Granjas', 1, 3),
    ('Manrique Central No. 2', 1, 3),
    ('Manrique Oriental', 1, 3),
    ('María Cano Carambolas', 1, 3),
    ('Oriente', 1, 3),
    ('Raizal', 1, 3),
    ('San José de la Cima No. 1', 1, 3),
    ('San José de la Cima No. 2', 1, 3),
    ('Santa Inés', 1, 3),
    ('Versalles No. 1', 1, 3),
    ('Versalles No. 2', 1, 3),

    ('Aranjuez', 1, 4),
    ('Berlín', 1, 4),
    ('Bermejal - Los Álamos', 1, 4),
    ('Brasilia', 1, 4),
    ('Campo Valdés No. 1', 1, 4),
    ('La Piñuela', 1, 4),
    ('Las Esmeraldas', 1, 4),
    ('Manrique Central No. 1', 1, 4),
    ('Miranda', 1, 4),
    ('Moravia', 1, 4),
    ('Palermo', 1, 4),
    ('San Isidro', 1, 4),
    ('San Pedro', 1, 4),
    ('Sevilla', 1, 4),

    ('Alfonso López', 1, 5),
    ('Belalcázar', 1, 5),
    ('Boyacá', 1, 5),
    ('Caribe', 1, 5),
    ('Castilla', 1, 5),
    ('El Progreso', 1, 5),
    ('Florencia', 1, 5),
    ('Francisco Antonio Zea', 1, 5),
    ('Girardot', 1, 5),
    ('Héctor Abad Gómez', 1, 5),
    ('Las Brisas', 1, 5),
    ('Tejelo', 1, 5),
    ('Toscana', 1, 5),
    ('Tricentenario', 1, 5),

    ('Doce de Octubre No. 1', 1, 6),
    ('Doce de Octubre No. 2', 1, 6),
    ('El Progreso No. 2', 1, 6),
    ('El Triunfo', 1, 6),
    ('Kennedy', 1, 6),
    ('La Esperanza', 1, 6),
    ('Mirador del Doce', 1, 6),
    ('Pedregal', 1, 6),
    ('Picachito', 1, 6),
    ('Picacho', 1, 6),
    ('San Martín de Porres', 1, 6),
    ('Santander', 1, 6),

    ('Altamira', 1, 7),
    ('Aures No. 1', 1, 7),
    ('Aures No. 2', 1, 7),
    ('Bello Horizonte', 1, 7),
    ('Bosques de San Pablo', 1, 7),
    ('Cerro El Volador', 1, 7),
    ('Cucaracho', 1, 7),
    ('Córdoba', 1, 7),
    ('El Diamante', 1, 7),
    ('Facultad de Minas Universidad Nacional', 1, 7),
    ('Fuente Clara', 1, 7),
    ('La Pilarica', 1, 7),
    ('López de Mesa', 1, 7),
    ('Monteclaro', 1, 7),
    ('Nueva Villa de la Iguaná', 1, 7),
    ('Olaya Herrera', 1, 7),
    ('Pajarito', 1, 7),
    ('Palenque', 1, 7),
    ('Robledo', 1, 7),
    ('San Germán', 1, 7),
    ('Santa Margarita', 1, 7),
    ('Villa Flora', 1, 7),

    ('Batallón Girardot', 1, 8),
    ('El Pinal', 1, 8),
    ('Enciso', 1, 8),
    ('La Ladera', 1, 8),
    ('La Libertad', 1, 8),
    ('La Mansión', 1, 8),
    ('La Sierra', 1, 8),
    ('Las Estancias', 1, 8),
    ('Llanaditas', 1, 8),
    ('Los Mangos', 1, 8),
    ('San Antonio', 1, 8),
    ('San Miguel', 1, 8),
    ('Sucre', 1, 8),
    ('Trece de Noviembre', 1, 8),
    ('Villa Hermosa', 1, 8),
    ('Villa Liliam', 1, 8),
    ('Villa Turbay', 1, 8),
    ('Villatina', 1, 8),

    ('Alejandro Echavarría', 1, 9),
    ('Asomadera No. 1', 1, 9),
    ('Asomadera No. 2', 1, 9),
    ('Asomadera No. 3', 1, 9),
    ('Barrio Caycedo', 1, 9),
    ('Barrios de Jesús', 1, 9),
    ('Bomboná No. 2', 1, 9),
    ('Buenos Aires', 1, 9),
    ('Cataluña', 1, 9),
    ('El Salvador', 1, 9),
    ('Gerona', 1, 9),
    ('Juan Pablo II', 1, 9),
    ('La Milagrosa', 1, 9),
    ('Loreto', 1, 9),
    ('Los Cerros El Vergel', 1, 9),
    ('Miraflores', 1, 9),
    ('Ocho de Marzo', 1, 9),

    ('Barrio Colón', 1, 10),
    ('Bomboná No. 1', 1, 10),
    ('Boston', 1, 10),
    ('Calle Nueva', 1, 10),
    ('Corazón de Jesús', 1, 10),
    ('El Chagualo', 1, 10),
    ('Estación Villa', 1, 10),
    ('Guayaquil', 1, 10),
    ('Jesús Nazareno', 1, 10),
    ('La Candelaria', 1, 10),
    ('Las Palmas', 1, 10),
    ('Los Ángeles', 1, 10),
    ('Perpetuo Socorro', 1, 10),
    ('Prado', 1, 10),
    ('San Benito', 1, 10),
    ('San Diego', 1, 10),
    ('Villa Nueva', 1, 10),

    ('Bolivariana', 1, 11),
    ('Carlos E. Restrepo', 1, 11),
    ('Cuarta Brigada', 1, 11),
    ('El Velódromo', 1, 11),
    ('Estadio', 1, 11),
    ('Florida Nueva', 1, 11),
    ('La Castellana', 1, 11),
    ('Las Acacias', 1, 11),
    ('Laureles', 1, 11),
    ('Lorena', 1, 11),
    ('Los Colores', 1, 11),
    ('Los Conquistadores', 1, 11),
    ('Naranjal', 1, 11),
    ('San Joaquín', 1, 11),
    ('Suramericana', 1, 11),

    ('Barrio Cristóbal', 1, 12),
    ('Calasanz', 1, 12),
    ('Calasanz Parte Alta', 1, 12),
    ('Campo Alegre', 1, 12),
    ('El Danubio', 1, 12),
    ('Ferrini', 1, 12),
    ('La América', 1, 12),
    ('La Floresta', 1, 12),
    ('Los Pinos', 1, 12),
    ('Santa Lucía', 1, 12),
    ('Santa Mónica', 1, 12),
    ('Santa Teresita', 1, 12),
    ('Simón Bolívar', 1, 12),

    ('Antonio Nariño', 1, 13),
    ('Belencito', 1, 13),
    ('Betania', 1, 13),
    ('Blanquizal', 1, 13),
    ('Eduardo Santos', 1, 13),
    ('El Corazón', 1, 13),
    ('El Pesebre', 1, 13),
    ('El Salado', 1, 13),
    ('El Socorro', 1, 13),
    ('Juan XXIII La Quiebra', 1, 13),
    ('La Independencia', 1, 13),
    ('La Pradera', 1, 13),
    ('Los Alcázares', 1, 13),
    ('Metropolitano', 1, 13),
    ('Nuevos Conquistadores', 1, 13),
    ('San Javier No. 1', 1, 13),
    ('San Javier No. 2', 1, 13),
    ('Santa Rosa de Lima', 1, 13),
    ('Veinte de Julio', 1, 13),

    ('Alejandría', 1, 14),
    ('Altos del Poblado', 1, 14),
    ('Astorga', 1, 14),
    ('Barrio Colombia', 1, 14),
    ('Castropol', 1, 14),
    ('El Castillo', 1, 14),
    ('El Diamante No. 2', 1, 14),
    ('El Poblado', 1, 14),
    ('El Tesoro', 1, 14),
    ('La Aguacatala', 1, 14),
    ('La Florida', 1, 14),
    ('Lalinde', 1, 14),
    ('Las Lomas No. 1', 1, 14),
    ('Las Lomas No. 2', 1, 14),
    ('Los Balsos No. 1', 1, 14),
    ('Los Balsos No. 2', 1, 14),
    ('Los Naranjos', 1, 14),
    ('Manila', 1, 14),
    ('Patio Bonito', 1, 14),
    ('San Lucas', 1, 14),
    ('Santa María de los Ángeles', 1, 14),
    ('Villa Carlota', 1, 14),

    ('Campo Amor', 1, 15),
    ('Cristo Rey', 1, 15),
    ('Guayabal', 1, 15),
    ('La Colina', 1, 15),
    ('Santa Fe', 1, 15),
    ('Tenche', 1, 15),
    ('Trinidad', 1, 15),

    ('Altavista', 1, 16),
    ('Belén', 1, 16),
    ('Cerro Nutibara', 1, 16),
    ('Diego Echavarría', 1, 16),
    ('El Nogal - Los Almendros', 1, 16),
    ('El Rincón', 1, 16),
    ('Fátima', 1, 16),
    ('Granada', 1, 16),
    ('La Gloria', 1, 16),
    ('La Hondonada', 1, 16),
    ('La Loma de Los Bernal', 1, 16),
    ('La Mota', 1, 16),
    ('La Palma', 1, 16),
    ('Las Mercedes', 1, 16),
    ('Las Playas', 1, 16),
    ('Las Violetas', 1, 16),
    ('Los Alpes', 1, 16),
    ('Miravalle', 1, 16),
    ('Nueva Villa del Aburrá', 1, 16),
    ('Rosales', 1, 16),
    ('San Bernardo', 1, 16);


-- BELLO

INSERT INTO neighborhoods (name, municipality_id, commune_id) VALUES
    ('El Cafetal', 2, 17),
    ('José Antonio Galán', 2, 17),
    ('La Esmeralda', 2, 17),
    ('La Maruchenga', 2, 17),
    ('La Pradera', 2, 17),
    ('Los Sauces', 2, 17),
    ('París', 2, 17),
    ('Salvador Allende', 2, 17),

    ('Barrio Nuevo', 2, 18),
    ('Gran Avenida', 2, 18),
    ('La Cabaña', 2, 18),
    ('La Cabañita', 2, 18),
    ('La Florida', 2, 18),
    ('La Madera', 2, 18),
    ('San José Obrero', 2, 18),
    ('Zona Industrial No. 1', 2, 18),

    ('Amazonía', 2, 19),
    ('Los Búcaros', 2, 19),
    ('Molinares', 2, 19),
    ('Salento', 2, 19),
    ('San Simón', 2, 19),
    ('Santa Ana', 2, 19),
    ('Serramonte', 2, 19),
    ('Villas de Occidente', 2, 19),
    ('Zona Industrial No. 2', 2, 19),

    ('Andalucía', 2, 20),
    ('Central', 2, 20),
    ('Centro', 2, 20),
    ('El Cairo', 2, 20),
    ('El Cóngolo', 2, 20),
    ('El Rosario', 2, 20),
    ('Espíritu Santo', 2, 20),
    ('La Estación', 2, 20),
    ('La Meseta', 2, 20),
    ('La Milagrosa', 2, 20),
    ('Las Granjas', 2, 20),
    ('López de Mesa', 2, 20),
    ('Manchester', 2, 20),
    ('Nazareth', 2, 20),
    ('Prado', 2, 20),
    ('Puerto Bello', 2, 20),
    ('Pérez', 2, 20),
    ('Rincón Santos', 2, 20),
    ('Suárez', 2, 20),
    ('Zona Industrial No. 3', 2, 20),

    ('Altavista', 2, 21),
    ('Aralias', 2, 21),
    ('Briceño', 2, 21),
    ('Buenos Aires', 2, 21),
    ('El Carmelo', 2, 21),
    ('El Paraíso', 2, 21),
    ('El Porvenir', 2, 21),
    ('El Trapiche', 2, 21),
    ('Hato Viejo', 2, 21),
    ('La Cumbre', 2, 21),
    ('La Primavera', 2, 21),
    ('Riachuelos', 2, 21),
    ('Urapanes', 2, 21),
    ('Valadares', 2, 21),
    ('Villa María', 2, 21),
    ('Villas de Comfenalco', 2, 21),

    ('Bellavista', 2, 22),
    ('El Ducado', 2, 22),
    ('Girasoles', 2, 22),
    ('La Aldea', 2, 22),
    ('Los Alpes', 2, 22),
    ('Pachelly', 2, 22),
    ('Playa Rica', 2, 22),
    ('San Gabriel', 2, 22),
    ('San Martín', 2, 22),
    ('Tierradentro', 2, 22),
    ('Villa Linda', 2, 22),
    ('Villas del Sol', 2, 22),

    ('Altos de Niquía', 2, 23),
    ('Altos de Quitasol', 2, 23),
    ('El Mirador', 2, 23),
    ('La Selva', 2, 23),
    ('Niquía Bifamiliares', 2, 23),

    ('Ciudad Niquía', 2, 24),
    ('Ciudadela del Norte', 2, 24),
    ('Hermosa Provincia', 2, 24),
    ('Panamericano', 2, 24),
    ('Terranova', 2, 24),
    ('Zona Industrial No. 4', 2, 24),

    ('El Trébol', 2, 25),
    ('Guasimalito', 2, 25),
    ('La Navarra', 2, 25),
    ('Zona Industrial No. 5', 2, 25),

    ('Alcalá', 2, 26),
    ('Cinco Estrellas', 2, 26),
    ('Estación Primera', 2, 26),
    ('Fontidueño', 2, 26),
    ('La Camila', 2, 26),
    ('La Mina', 2, 26),
    ('La Virginia', 2, 26),
    ('Las Vegas', 2, 26),
    ('Los Ciruelos', 2, 26),
    ('Marco Fidel Suárez', 2, 26),
    ('Zona Industrial No. 6', 2, 26),

    ('Acevedo', 2, 27),
    ('Alpes del Norte', 2, 27),
    ('Belvedere', 2, 27),
    ('La Gabriela', 2, 27),
    ('Santa Rita', 2, 27),
    ('Zamora', 2, 27),
    ('Zona Industrial No. 7', 2, 27);


-- ENVIGADO

INSERT INTO neighborhoods (name, municipality_id, commune_id) VALUES
    ('Alcalá', 3, NULL),
    ('Alto de Misael', 3, NULL),
    ('Bosques de Zúñiga', 3, NULL),
    ('Bucarest', 3, NULL),
    ('El Chinguí', 3, NULL),
    ('El Chocho', 3, NULL),
    ('El Dorado', 3, NULL),
    ('El Esmeraldal', 3, NULL),
    ('El Portal', 3, NULL),
    ('El Salado', 3, NULL),
    ('El Trianón', 3, NULL),
    ('Jardines', 3, NULL),
    ('La Inmaculada', 3, NULL),
    ('La Magnolia', 3, NULL),
    ('La Mina', 3, NULL),
    ('La Orquídea', 3, NULL),
    ('La Paz', 3, NULL),
    ('La Pradera', 3, NULL),
    ('La Sebastiana', 3, NULL),
    ('Las Antillas', 3, NULL),
    ('Las Casitas', 3, NULL),
    ('Las Flores', 3, NULL),
    ('Las Vegas', 3, NULL),
    ('Loma de las Brujas', 3, NULL),
    ('Loma del Atravesado', 3, NULL),
    ('Loma del Barro', 3, NULL),
    ('Los Naranjos', 3, NULL),
    ('Mesa', 3, NULL),
    ('Milán Vallejuelos', 3, NULL),
    ('Obrero', 3, NULL),
    ('Pontevedra', 3, NULL),
    ('Primavera', 3, NULL),
    ('San José', 3, NULL),
    ('San Marcos', 3, NULL),
    ('San Rafael', 3, NULL),
    ('Uribe Ángel', 3, NULL),
    ('Villagrande', 3, NULL),
    ('Zona Centro', 3, NULL),
    ('Zúñiga', 3, NULL);


-- ITAGÜÍ

INSERT INTO neighborhoods (name, municipality_id, commune_id) VALUES
    ('Araucaria', 4, 28),
    ('Artex', 4, 28),
    ('Asturias', 4, 28),
    ('Centro', 4, 28),
    ('La Gloria', 4, 28),
    ('La Independencia', 4, 28),
    ('Las Mercedes', 4, 28),
    ('Los Naranjos', 4, 28),
    ('Playa Rica', 4, 28),
    ('San Isidro', 4, 28),
    ('San José', 4, 28),
    ('San Juan Bautista', 4, 28),
    ('La Santa Cruz', 4, 28),
    ('Satexco', 4, 28),
    ('Villa Paula', 4, 28),
    ('Zona Industrial No. 1', 4, 28),
    ('Zona Industrial No. 2', 4, 28),
    ('Camparola', 4, 29),
    ('El Palmar', 4, 29),
    ('Montesacro', 4, 29),
    ('La Finca', 4, 29),
    ('La Palma', 4, 29),
    ('Las Margaritas', 4, 29),
    ('Malta', 4, 29),
    ('Monteverde', 4, 29),
    ('Samaria Robles del Sur', 4, 29),
    ('Samaria', 4, 29),
    ('San Pío X', 4, 29),
    ('Santa Ana', 4, 29),
    ('Santa Catalina', 4, 29),
    ('Yarumito', 4, 29),
    ('Zona Industrial No. 3', 4, 29),
    ('19 de Abril', 4, 30),
    ('Bariloche', 4, 30),
    ('Ditaires', 4, 30),
    ('Glorieta Pilsen', 4, 30),
    ('Las Brisas', 4, 30),
    ('Pilsen', 4, 30),
    ('Reserva Campestre', 4, 30),
    ('San Agustín', 4, 30),
    ('San Antonio', 4, 30),
    ('San Francisco', 4, 30),
    ('San Gabriel', 4, 30),
    ('San Javier', 4, 30),
    ('Triana', 4, 30),
    ('Villa Lía', 4, 30),
    ('Villas de San Antonio', 4, 30),
    ('Colinas del Sur', 4, 31),
    ('El Carmelo', 4, 31),
    ('El Guayabo', 4, 31),
    ('La Esmeralda', 4, 31),
    ('La Hortensia', 4, 31),
    ('La Mayorista', 4, 31),
    ('San Fernando', 4, 31),
    ('Santa María No. 1', 4, 31),
    ('Santa María No. 2', 4, 31),
    ('Santa María No. 3', 4, 31),
    ('Simón Bolívar', 4, 31),
    ('Villa Ventura', 4, 31),
    ('Viviendas del Sur', 4, 31),
    ('Balcones de Sevilla', 4, 32),
    ('Calatrava', 4, 32),
    ('El Tablazo', 4, 32),
    ('Ferrara', 4, 32),
    ('La Aldea', 4, 32),
    ('Las Acacias', 4, 32),
    ('Las Américas', 4, 32),
    ('Loma Linda', 4, 32),
    ('Terranova', 4, 32),
    ('El Progreso', 4, 33),
    ('El Rosario', 4, 33),
    ('Fátima', 4, 33),
    ('La Unión', 4, 33),
    ('Loma de los Zuleta', 4, 33),
    ('Los Olivares', 4, 33),
    ('Santa María La Nueva', 4, 33),
    ('Del Valle', 4, 34),
    ('El Arenal', 4, 34),
    ('El Porvenir 1', 4, 34),
    ('El Porvenir 2', 4, 34),
    ('Jardines de San José', 4, 34),
    ('Las Villas', 4, 34),
    ('San Pablo', 4, 34),
    ('Tierra Verde', 4, 34);


-- SABANETA

INSERT INTO neighborhoods (name, municipality_id, commune_id) VALUES
    ('Aliadas del Sur', 5, NULL),
    ('Ancón Sur', 5, NULL),
    ('Betania', 5, NULL),
    ('Calle del Banco', 5, NULL),
    ('Calle Larga', 5, NULL),
    ('El Carmelo', 5, NULL),
    ('Entreamigos', 5, NULL),
    ('Holanda', 5, NULL),
    ('La Barquereña', 5, NULL),
    ('La Florida', 5, NULL),
    ('Lagos de la Doctora', 5, NULL),
    ('Las Casitas', 5, NULL),
    ('Los Alcázares', 5, NULL),
    ('Los Arias', 5, NULL),
    ('Manuel Restrepo', 5, NULL),
    ('María Auxiliadora', 5, NULL),
    ('Nuestra Señora de los Dolores', 5, NULL),
    ('Paso Ancho', 5, NULL),
    ('Playas de María', 5, NULL),
    ('Prados de Sabaneta', 5, NULL),
    ('Promisión', 5, NULL),
    ('Restrepo Naranjo', 5, NULL),
    ('Sabaneta Real', 5, NULL),
    ('San Joaquín', 5, NULL),
    ('San Rafael', 5, NULL),
    ('Santa Ana', 5, NULL),
    ('Tres Esquinas', 5, NULL),
    ('Vegas de la Doctora', 5, NULL),
    ('Vegas de San José', 5, NULL),
    ('Villas del Carmen', 5, NULL),
    ('Virgen del Carmen', 5, NULL);


-- LA ESTRELLA

INSERT INTO neighborhoods (name, municipality_id, commune_id) VALUES
    ('Alto de los Ospina', 6, NULL),
    ('Ancón San Martín', 6, NULL),
    ('Ancón Sur', 6, NULL),
    ('Bellavista', 6, NULL),
    ('Bellos Aires', 6, NULL),
    ('Calle Vieja', 6, NULL),
    ('Camilo Torres', 6, NULL),
    ('Campoalegre', 6, NULL),
    ('Caquetá', 6, NULL),
    ('Centro', 6, NULL),
    ('Centro-Pueblo Viejo', 6, NULL),
    ('Chile', 6, NULL),
    ('El Dorado', 6, NULL),
    ('El Pedrero', 6, NULL),
    ('Escobar', 6, NULL),
    ('Horizontes', 6, NULL),
    ('Industrial', 6, NULL),
    ('Juan XXIII', 6, NULL),
    ('La Bermejala', 6, NULL),
    ('La Chinca', 6, NULL),
    ('La Ferrería', 6, NULL),
    ('La Inmaculada 1', 6, NULL),
    ('La Inmaculada 2', 6, NULL),
    ('La Ospina', 6, NULL),
    ('La Raya', 6, NULL),
    ('Las Brisas', 6, NULL),
    ('Los Chanos', 6, NULL),
    ('Monterrey', 6, NULL),
    ('Pan de Azúcar', 6, NULL),
    ('Peñas Blancas', 6, NULL),
    ('Primavera', 6, NULL),
    ('Quebrada Grande', 6, NULL),
    ('San Agustín', 6, NULL),
    ('San Andrés', 6, NULL),
    ('San Antonio', 6, NULL),
    ('San Cayetano', 6, NULL),
    ('San Francisco', 6, NULL),
    ('San Isidro', 6, NULL),
    ('San Vicente', 6, NULL),
    ('Tablaza', 6, NULL),
    ('Tierra Amarilla', 6, NULL),
    ('Toledo', 6, NULL),
    ('Tres Esquinas', 6, NULL),
    ('Villa Alicia', 6, NULL),
    ('Villa Campestre', 6, NULL),
    ('Villa Mira', 6, NULL),
    ('Alto de la Cruz', 6, NULL),
    ('Ancón La Playa', 6, NULL),
    ('Ancón Selene', 6, NULL),
    ('Calle del Tiro', 6, NULL),
    ('Callejón de los Flórez', 6, NULL),
    ('Claro Verde', 6, NULL),
    ('El Cerrito', 6, NULL),
    ('El Rosario', 6, NULL),
    ('Flores del Campo', 6, NULL),
    ('Hoyo de Buga', 6, NULL),
    ('La Carrilera', 6, NULL),
    ('La Playita', 6, NULL),
    ('Los Balsos', 6, NULL),
    ('Los Sauces', 6, NULL),
    ('Montañita', 6, NULL),
    ('San Diego', 6, NULL),
    ('Tarapacá', 6, NULL);


-- CALDAS: BARRIOS Y SECTORES URBANOS DEL DIAGNÓSTICO MUNICIPAL

INSERT INTO neighborhoods (name, municipality_id, commune_id) VALUES
    ('Andalucía', 7, NULL),
    ('Barrios Unidos', 7, NULL),
    ('Bellavista', 7, NULL),
    ('Buena Esperanza', 7, NULL),
    ('Centenario', 7, NULL),
    ('Centro', 7, NULL),
    ('Ciudadela Real', 7, NULL),
    ('Cristo Rey', 7, NULL),
    ('El Cano', 7, NULL),
    ('El Pombal', 7, NULL),
    ('El Porvenir', 7, NULL),
    ('El Socorro', 7, NULL),
    ('Felipe Echavarría No. 1', 7, NULL),
    ('Felipe Echavarría No. 2', 7, NULL),
    ('Fundadores', 7, NULL),
    ('Goretti', 7, NULL),
    ('Juan XXIII', 7, NULL),
    ('La Acuarela Río', 7, NULL),
    ('La Aguacatala', 7, NULL),
    ('La Chuscala', 7, NULL),
    ('La Corrala El Hoyo', 7, NULL),
    ('La Corrala Parte Baja', 7, NULL),
    ('La Docena', 7, NULL),
    ('La Gitana', 7, NULL),
    ('La Inmaculada 1', 7, NULL),
    ('La Inmaculada 2', 7, NULL),
    ('La Mansión', 7, NULL),
    ('La Planta', 7, NULL),
    ('La Playita', 7, NULL),
    ('La Raya Norte', 7, NULL),
    ('La Rivera', 7, NULL),
    ('La Salle', 7, NULL),
    ('Las Margaritas', 7, NULL),
    ('Locería', 7, NULL),
    ('Locería Colombiana', 7, NULL),
    ('Los Cerezos', 7, NULL),
    ('Los Cerezos La Bombonera', 7, NULL),
    ('Mandalay Parte Alta', 7, NULL),
    ('Mandalay Parte Baja', 7, NULL),
    ('Mandalay Parte Media', 7, NULL),
    ('Olaya Herrera', 7, NULL),
    ('Primavera', 7, NULL),
    ('San Judas', 7, NULL),
    ('Villacapri', 7, NULL),
    ('Barrio Nuevo El Cerrito', 7, NULL),
    ('Kachotis', 7, NULL),
    ('La Almería', 7, NULL),
    ('La Corrala I', 7, NULL),
    ('La Corrala II', 7, NULL),
    ('La Corrala III', 7, NULL),
    ('Minuto de Dios', 7, NULL),
    ('San Miguel', 7, NULL),
    ('Tres Aguas', 7, NULL);


-- COPACABANA

INSERT INTO neighborhoods (name, municipality_id, commune_id) VALUES
    ('Cristo Rey', 8, NULL),
    ('El Mojón', 8, NULL),
    ('El Porvenir', 8, NULL),
    ('El Recreo', 8, NULL),
    ('El Remanso', 8, NULL),
    ('Fátima', 8, NULL),
    ('La Asunción', 8, NULL),
    ('La Azulita', 8, NULL),
    ('La Misericordia', 8, NULL),
    ('Las Vegas', 8, NULL),
    ('Machado', 8, NULL),
    ('María', 8, NULL),
    ('Miraflores', 8, NULL),
    ('Obrero', 8, NULL),
    ('Pedregal', 8, NULL),
    ('Pedrera', 8, NULL),
    ('San Francisco', 8, NULL),
    ('San Juan', 8, NULL),
    ('Simón Bolívar', 8, NULL),
    ('Tablazo', 8, NULL),
    ('Tobón Quintero', 8, NULL),
    ('Villanueva', 8, NULL),
    ('Yarumito', 8, NULL);


-- GIRARDOTA

INSERT INTO neighborhoods (name, municipality_id, commune_id) VALUES
    ('Aurelio Mejía', 9, NULL),
    ('Centro', 9, NULL),
    ('El Llano', 9, NULL),
    ('El Naranjal', 9, NULL),
    ('El Paraíso', 9, NULL),
    ('El Salado', 9, NULL),
    ('Girardota la Nueva', 9, NULL),
    ('Guaduales', 9, NULL),
    ('Guayacanes', 9, NULL),
    ('Juan XXIII', 9, NULL),
    ('La Ceiba', 9, NULL),
    ('La Ferrería', 9, NULL),
    ('La Florida', 9, NULL),
    ('Montecarlo', 9, NULL),
    ('Nuevo Horizonte', 9, NULL),
    ('San José', 9, NULL),
    ('Santa Ana', 9, NULL),
    ('Palmas del Llano', 9, NULL),
    ('Juan Pablo II', 9, NULL),
    ('Llano Azul', 9, NULL),
    ('Campo Nuevo', 9, NULL);


-- BARBOSA

INSERT INTO neighborhoods (name, municipality_id, commune_id) VALUES
    ('30 de Mayo', 10, NULL),
    ('Aguas Calientes', 10, NULL),
    ('Barrios de Jesús', 10, NULL),
    ('Buenos Aires', 10, NULL),
    ('Cecilia Caballeros', 10, NULL),
    ('Centro', 10, NULL),
    ('El Portón', 10, NULL),
    ('El Progreso', 10, NULL),
    ('La Esmeralda', 10, NULL),
    ('Leticia', 10, NULL),
    ('Pepe Sierra I', 10, NULL),
    ('Pepe Sierra II', 10, NULL),
    ('Robles', 10, NULL),
    ('Santa Mónica', 10, NULL),
    ('Santiago de Caballeros', 10, NULL);


