from typing import Protocol
from api.contracts import AddressComponentsInput, AddressCreateInput
from api.models import Address

class AddressRepositoryInterface(Protocol):
    def get_by_id(self, address_id: int) -> Address | None: ...
    def find_by_components(self, components: AddressComponentsInput) -> Address | None: ...
    def list_by_neighborhood(self, neighborhood_id: int) -> list[Address]: ...
    def create(self, data: AddressCreateInput) -> Address: ...
