from typing import Protocol
from api.contracts import CrewCreateInput, CrewMemberInput, CrewMemberOutput, CrewOutput, CrewUpdateInput, ExecutionContext, OperationResult


class CrewServiceInterface(Protocol):
    def get_by_id(self, context: ExecutionContext, crew_id: int) -> OperationResult[CrewOutput]: ...
    def list_all(self, context: ExecutionContext) -> OperationResult[list[CrewOutput]]: ...
    def create(self, context: ExecutionContext, data: CrewCreateInput) -> OperationResult[CrewOutput]: ...
    def update(self, context: ExecutionContext, data: CrewUpdateInput) -> OperationResult[CrewOutput]: ...
    def get_membership(self, context: ExecutionContext, user_id: int) -> OperationResult[CrewMemberOutput | None]: ...
    def list_members(self, context: ExecutionContext, crew_id: int) -> OperationResult[list[CrewMemberOutput]]: ...
    def add_member(self, context: ExecutionContext, data: CrewMemberInput) -> OperationResult[CrewMemberOutput]: ...
    def change_crew(self, context: ExecutionContext, data: CrewMemberInput) -> OperationResult[CrewMemberOutput]: ...
    def remove_member(self, context: ExecutionContext, user_id: int) -> OperationResult[bool]: ...
