from typing import Protocol
from api.contracts import ExecutionContext, OperationResult, UserActivationInput, UserCreateInput, UserFilters, UserOutput, UserUpdateInput


class UserServiceInterface(Protocol):
    def get_by_id(self, context: ExecutionContext, user_id: int) -> OperationResult[UserOutput]: ...
    def get_by_email(self, context: ExecutionContext, email: str) -> OperationResult[UserOutput]: ...
    def list_by_filters(self, context: ExecutionContext, filters: UserFilters | None = None) -> OperationResult[list[UserOutput]]: ...
    def create(self, context: ExecutionContext, data: UserCreateInput) -> OperationResult[UserOutput]: ...
    def update(self, context: ExecutionContext, data: UserUpdateInput) -> OperationResult[UserOutput]: ...
    def set_active(self, context: ExecutionContext, data: UserActivationInput) -> OperationResult[UserOutput]: ...
